# Generated by Django 3.0.8 on 2020-10-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('mob_no', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
